/**
 * Seshat Swarm — Compiled Behavioral Catalog
 *
 * AUTO-GENERATED by scripts/compile-catalog.ts
 * DO NOT EDIT MANUALLY — regenerate with: pnpm compile-catalog
 * Generated: 2026-02-09T04:36:05.766Z
 * Patterns: 50
 */

#ifndef SESHAT_CATALOG_DATA_H
#define SESHAT_CATALOG_DATA_H

#include "types.h"

#define CATALOG_SIZE 50

static const PatternEntry CATALOG[CATALOG_SIZE] = {
    /* [0] avoid-emergency-performer-bare.crazyflie-2.1 */
    {
        .id = 0,
        .generator_type = 6,
        ._pad = 0,
        .defaults = { 0.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.2f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.0f,
        .pos_quality_floor = 0.0f,
    },
    /* [1] avoid-emergency-performer-bare.sim-gazebo */
    {
        .id = 1,
        .generator_type = 6,
        ._pad = 0,
        .defaults = { 0.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.2f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.0f,
        .pos_quality_floor = 0.0f,
    },
    /* [2] dock-autonomous-charger-inbound-bare.crazyflie-2.1 */
    {
        .id = 2,
        .generator_type = 1,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.03f,
        .pos_quality_floor = 0.7f,
    },
    /* [3] docked-autonomous-charging-bare.crazyflie-2.1 */
    {
        .id = 3,
        .generator_type = 7,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.0f,
        .pos_quality_floor = 0.0f,
    },
    /* [4] formation-hold-autonomous-follower-bare.crazyflie-2.1 */
    {
        .id = 4,
        .generator_type = 3,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { -2.0f, -2.0f, -2.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 2.0f, 2.0f, 2.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.2f,
        .pos_quality_floor = 0.5f,
    },
    /* [5] formation-hold-autonomous-follower-bare.sim-gazebo */
    {
        .id = 5,
        .generator_type = 3,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { -2.0f, -2.0f, -2.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 2.0f, 2.0f, 2.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.2f,
        .pos_quality_floor = 0.5f,
    },
    /* [6] formation-hold-autonomous-performer-bare.crazyflie-2.1 */
    {
        .id = 6,
        .generator_type = 3,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { -2.0f, -2.0f, -2.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 2.0f, 2.0f, 2.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.2f,
        .pos_quality_floor = 0.5f,
    },
    /* [7] formation-hold-autonomous-performer-bare.sim-gazebo */
    {
        .id = 7,
        .generator_type = 3,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { -2.0f, -2.0f, -2.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 2.0f, 2.0f, 2.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.2f,
        .pos_quality_floor = 0.5f,
    },
    /* [8] formation-transition-autonomous-follower-bare.crazyflie-2.1 */
    {
        .id = 8,
        .generator_type = 5,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.2f,
        .pos_quality_floor = 0.5f,
    },
    /* [9] formation-transition-autonomous-performer-bare.crazyflie-2.1 */
    {
        .id = 9,
        .generator_type = 5,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.2f,
        .pos_quality_floor = 0.5f,
    },
    /* [10] grounded-autonomous-reserve-bare.crazyflie-2.1 */
    {
        .id = 10,
        .generator_type = 7,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.0f,
        .pos_quality_floor = 0.0f,
    },
    /* [11] grounded-autonomous-reserve-bare.sim-gazebo */
    {
        .id = 11,
        .generator_type = 7,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.0f,
        .pos_quality_floor = 0.0f,
    },
    /* [12] hover-autonomous-anchor-bare.crazyflie-2.1 */
    {
        .id = 12,
        .generator_type = 0,
        ._pad = 0,
        .defaults = { 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.2f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 2.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.2f,
        .pos_quality_floor = 0.6f,
    },
    /* [13] hover-autonomous-charger-inbound-bare.crazyflie-2.1 */
    {
        .id = 13,
        .generator_type = 0,
        ._pad = 0,
        .defaults = { 0.4f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.2f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.05f,
        .pos_quality_floor = 0.5f,
    },
    /* [14] hover-autonomous-charger-outbound-bare.crazyflie-2.1 */
    {
        .id = 14,
        .generator_type = 0,
        ._pad = 0,
        .defaults = { 0.6f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.3f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 1.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.5f,
        .pos_quality_floor = 0.5f,
    },
    /* [15] hover-autonomous-charging-bare.crazyflie-2.1 */
    {
        .id = 15,
        .generator_type = 0,
        ._pad = 0,
        .defaults = { 0.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.3f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.05f,
        .pos_quality_floor = 0.5f,
    },
    /* [16] hover-autonomous-follower-bare.crazyflie-2.1 */
    {
        .id = 16,
        .generator_type = 0,
        ._pad = 0,
        .defaults = { 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.2f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 2.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.15f,
        .pos_quality_floor = 0.5f,
    },
    /* [17] hover-autonomous-follower-bare.sim-gazebo */
    {
        .id = 17,
        .generator_type = 0,
        ._pad = 0,
        .defaults = { 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.2f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 2.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.15f,
        .pos_quality_floor = 0.5f,
    },
    /* [18] hover-autonomous-leader-bare.crazyflie-2.1 */
    {
        .id = 18,
        .generator_type = 0,
        ._pad = 0,
        .defaults = { 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.2f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 2.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.2f,
        .pos_quality_floor = 0.6f,
    },
    /* [19] hover-autonomous-leader-bare.sim-gazebo */
    {
        .id = 19,
        .generator_type = 0,
        ._pad = 0,
        .defaults = { 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.2f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 2.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.2f,
        .pos_quality_floor = 0.6f,
    },
    /* [20] hover-autonomous-performer-bare.crazyflie-2.1 */
    {
        .id = 20,
        .generator_type = 0,
        ._pad = 0,
        .defaults = { 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.2f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 2.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.15f,
        .pos_quality_floor = 0.5f,
    },
    /* [21] hover-autonomous-performer-bare.sim-gazebo */
    {
        .id = 21,
        .generator_type = 0,
        ._pad = 0,
        .defaults = { 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.2f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 2.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.15f,
        .pos_quality_floor = 0.5f,
    },
    /* [22] hover-autonomous-relay-bare.crazyflie-2.1 */
    {
        .id = 22,
        .generator_type = 0,
        ._pad = 0,
        .defaults = { 1.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 2.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.2f,
        .pos_quality_floor = 0.5f,
    },
    /* [23] hover-autonomous-reserve-bare.crazyflie-2.1 */
    {
        .id = 23,
        .generator_type = 0,
        ._pad = 0,
        .defaults = { 0.8f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.2f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 2.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.3f,
        .pos_quality_floor = 0.5f,
    },
    /* [24] hover-emergency-performer-bare.crazyflie-2.1 */
    {
        .id = 24,
        .generator_type = 0,
        ._pad = 0,
        .defaults = { 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.2f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 2.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.0f,
        .pos_quality_floor = 0.0f,
    },
    /* [25] hover-emergency-performer-bare.sim-gazebo */
    {
        .id = 25,
        .generator_type = 0,
        ._pad = 0,
        .defaults = { 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.2f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 2.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.0f,
        .pos_quality_floor = 0.0f,
    },
    /* [26] hover-operator-guided-performer-bare.crazyflie-2.1 */
    {
        .id = 26,
        .generator_type = 0,
        ._pad = 0,
        .defaults = { 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.2f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 2.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.15f,
        .pos_quality_floor = 0.5f,
    },
    /* [27] land-autonomous-performer-bare.crazyflie-2.1 */
    {
        .id = 27,
        .generator_type = 1,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.05f,
        .pos_quality_floor = 0.3f,
    },
    /* [28] land-autonomous-performer-bare.sim-gazebo */
    {
        .id = 28,
        .generator_type = 1,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.05f,
        .pos_quality_floor = 0.3f,
    },
    /* [29] land-emergency-performer-bare.crazyflie-2.1 */
    {
        .id = 29,
        .generator_type = 1,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.0f,
        .pos_quality_floor = 0.0f,
    },
    /* [30] land-emergency-performer-bare.sim-gazebo */
    {
        .id = 30,
        .generator_type = 1,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.0f,
        .pos_quality_floor = 0.0f,
    },
    /* [31] orbit-autonomous-follower-bare.crazyflie-2.1 */
    {
        .id = 31,
        .generator_type = 4,
        ._pad = 0,
        .defaults = { 0.5f, 0.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.3f, 0.1f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 1.5f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.2f,
        .pos_quality_floor = 0.5f,
    },
    /* [32] orbit-autonomous-performer-bare.crazyflie-2.1 */
    {
        .id = 32,
        .generator_type = 4,
        ._pad = 0,
        .defaults = { 0.5f, 0.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.3f, 0.1f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 1.5f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.2f,
        .pos_quality_floor = 0.5f,
    },
    /* [33] orbit-autonomous-performer-bare.sim-gazebo */
    {
        .id = 33,
        .generator_type = 4,
        ._pad = 0,
        .defaults = { 0.5f, 0.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.3f, 0.1f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 1.5f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.2f,
        .pos_quality_floor = 0.5f,
    },
    /* [34] orbit-operator-guided-performer-bare.crazyflie-2.1 */
    {
        .id = 34,
        .generator_type = 4,
        ._pad = 0,
        .defaults = { 0.5f, 0.3f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.3f, 0.1f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 1.5f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.2f,
        .pos_quality_floor = 0.5f,
    },
    /* [35] relay-hold-autonomous-relay-bare.crazyflie-2.1 */
    {
        .id = 35,
        .generator_type = 0,
        ._pad = 0,
        .defaults = { 1.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 2.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.2f,
        .pos_quality_floor = 0.5f,
    },
    /* [36] relay-hold-autonomous-relay-bare.sim-gazebo */
    {
        .id = 36,
        .generator_type = 0,
        ._pad = 0,
        .defaults = { 1.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 2.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.2f,
        .pos_quality_floor = 0.5f,
    },
    /* [37] takeoff-autonomous-performer-bare.crazyflie-2.1 */
    {
        .id = 37,
        .generator_type = 1,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.3f,
        .pos_quality_floor = 0.6f,
    },
    /* [38] takeoff-autonomous-performer-bare.sim-gazebo */
    {
        .id = 38,
        .generator_type = 1,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.3f,
        .pos_quality_floor = 0.6f,
    },
    /* [39] translate-autonomous-charger-inbound-bare.crazyflie-2.1 */
    {
        .id = 39,
        .generator_type = 1,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.08f,
        .pos_quality_floor = 0.4f,
    },
    /* [40] translate-autonomous-charger-outbound-bare.crazyflie-2.1 */
    {
        .id = 40,
        .generator_type = 1,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.5f,
        .pos_quality_floor = 0.5f,
    },
    /* [41] translate-autonomous-follower-bare.crazyflie-2.1 */
    {
        .id = 41,
        .generator_type = 1,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.2f,
        .pos_quality_floor = 0.5f,
    },
    /* [42] translate-autonomous-follower-bare.sim-gazebo */
    {
        .id = 42,
        .generator_type = 1,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.2f,
        .pos_quality_floor = 0.5f,
    },
    /* [43] translate-autonomous-leader-bare.crazyflie-2.1 */
    {
        .id = 43,
        .generator_type = 1,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.25f,
        .pos_quality_floor = 0.6f,
    },
    /* [44] translate-autonomous-leader-bare.sim-gazebo */
    {
        .id = 44,
        .generator_type = 1,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.25f,
        .pos_quality_floor = 0.6f,
    },
    /* [45] translate-autonomous-performer-bare.crazyflie-2.1 */
    {
        .id = 45,
        .generator_type = 1,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.2f,
        .pos_quality_floor = 0.5f,
    },
    /* [46] translate-autonomous-performer-bare.sim-gazebo */
    {
        .id = 46,
        .generator_type = 1,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.2f,
        .pos_quality_floor = 0.5f,
    },
    /* [47] translate-autonomous-relay-bare.crazyflie-2.1 */
    {
        .id = 47,
        .generator_type = 1,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.2f,
        .pos_quality_floor = 0.5f,
    },
    /* [48] translate-operator-guided-performer-bare.crazyflie-2.1 */
    {
        .id = 48,
        .generator_type = 1,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.2f,
        .pos_quality_floor = 0.5f,
    },
    /* [49] undock-autonomous-charger-outbound-bare.crazyflie-2.1 */
    {
        .id = 49,
        .generator_type = 1,
        ._pad = 0,
        .defaults = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_min = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .bounds_max = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
        .battery_floor = 0.5f,
        .pos_quality_floor = 0.6f,
    },
};

/* Pattern ID defines (for firmware code readability) */
#define PATTERN_AVOID_EMERGENCY_PERFORMER_BARE_CRAZYFLIE_2_1 0
#define PATTERN_AVOID_EMERGENCY_PERFORMER_BARE_SIM_GAZEBO 1
#define PATTERN_DOCK_AUTONOMOUS_CHARGER_INBOUND_BARE_CRAZYFLIE_2_1 2
#define PATTERN_DOCKED_AUTONOMOUS_CHARGING_BARE_CRAZYFLIE_2_1 3
#define PATTERN_FORMATION_HOLD_AUTONOMOUS_FOLLOWER_BARE_CRAZYFLIE_2_1 4
#define PATTERN_FORMATION_HOLD_AUTONOMOUS_FOLLOWER_BARE_SIM_GAZEBO 5
#define PATTERN_FORMATION_HOLD_AUTONOMOUS_PERFORMER_BARE_CRAZYFLIE_2_1 6
#define PATTERN_FORMATION_HOLD_AUTONOMOUS_PERFORMER_BARE_SIM_GAZEBO 7
#define PATTERN_FORMATION_TRANSITION_AUTONOMOUS_FOLLOWER_BARE_CRAZYFLIE_2_1 8
#define PATTERN_FORMATION_TRANSITION_AUTONOMOUS_PERFORMER_BARE_CRAZYFLIE_2_1 9
#define PATTERN_GROUNDED_AUTONOMOUS_RESERVE_BARE_CRAZYFLIE_2_1 10
#define PATTERN_GROUNDED_AUTONOMOUS_RESERVE_BARE_SIM_GAZEBO 11
#define PATTERN_HOVER_AUTONOMOUS_ANCHOR_BARE_CRAZYFLIE_2_1 12
#define PATTERN_HOVER_AUTONOMOUS_CHARGER_INBOUND_BARE_CRAZYFLIE_2_1 13
#define PATTERN_HOVER_AUTONOMOUS_CHARGER_OUTBOUND_BARE_CRAZYFLIE_2_1 14
#define PATTERN_HOVER_AUTONOMOUS_CHARGING_BARE_CRAZYFLIE_2_1 15
#define PATTERN_HOVER_AUTONOMOUS_FOLLOWER_BARE_CRAZYFLIE_2_1 16
#define PATTERN_HOVER_AUTONOMOUS_FOLLOWER_BARE_SIM_GAZEBO 17
#define PATTERN_HOVER_AUTONOMOUS_LEADER_BARE_CRAZYFLIE_2_1 18
#define PATTERN_HOVER_AUTONOMOUS_LEADER_BARE_SIM_GAZEBO 19
#define PATTERN_HOVER_AUTONOMOUS_PERFORMER_BARE_CRAZYFLIE_2_1 20
#define PATTERN_HOVER_AUTONOMOUS_PERFORMER_BARE_SIM_GAZEBO 21
#define PATTERN_HOVER_AUTONOMOUS_RELAY_BARE_CRAZYFLIE_2_1 22
#define PATTERN_HOVER_AUTONOMOUS_RESERVE_BARE_CRAZYFLIE_2_1 23
#define PATTERN_HOVER_EMERGENCY_PERFORMER_BARE_CRAZYFLIE_2_1 24
#define PATTERN_HOVER_EMERGENCY_PERFORMER_BARE_SIM_GAZEBO 25
#define PATTERN_HOVER_OPERATOR_GUIDED_PERFORMER_BARE_CRAZYFLIE_2_1 26
#define PATTERN_LAND_AUTONOMOUS_PERFORMER_BARE_CRAZYFLIE_2_1 27
#define PATTERN_LAND_AUTONOMOUS_PERFORMER_BARE_SIM_GAZEBO 28
#define PATTERN_LAND_EMERGENCY_PERFORMER_BARE_CRAZYFLIE_2_1 29
#define PATTERN_LAND_EMERGENCY_PERFORMER_BARE_SIM_GAZEBO 30
#define PATTERN_ORBIT_AUTONOMOUS_FOLLOWER_BARE_CRAZYFLIE_2_1 31
#define PATTERN_ORBIT_AUTONOMOUS_PERFORMER_BARE_CRAZYFLIE_2_1 32
#define PATTERN_ORBIT_AUTONOMOUS_PERFORMER_BARE_SIM_GAZEBO 33
#define PATTERN_ORBIT_OPERATOR_GUIDED_PERFORMER_BARE_CRAZYFLIE_2_1 34
#define PATTERN_RELAY_HOLD_AUTONOMOUS_RELAY_BARE_CRAZYFLIE_2_1 35
#define PATTERN_RELAY_HOLD_AUTONOMOUS_RELAY_BARE_SIM_GAZEBO 36
#define PATTERN_TAKEOFF_AUTONOMOUS_PERFORMER_BARE_CRAZYFLIE_2_1 37
#define PATTERN_TAKEOFF_AUTONOMOUS_PERFORMER_BARE_SIM_GAZEBO 38
#define PATTERN_TRANSLATE_AUTONOMOUS_CHARGER_INBOUND_BARE_CRAZYFLIE_2_1 39
#define PATTERN_TRANSLATE_AUTONOMOUS_CHARGER_OUTBOUND_BARE_CRAZYFLIE_2_1 40
#define PATTERN_TRANSLATE_AUTONOMOUS_FOLLOWER_BARE_CRAZYFLIE_2_1 41
#define PATTERN_TRANSLATE_AUTONOMOUS_FOLLOWER_BARE_SIM_GAZEBO 42
#define PATTERN_TRANSLATE_AUTONOMOUS_LEADER_BARE_CRAZYFLIE_2_1 43
#define PATTERN_TRANSLATE_AUTONOMOUS_LEADER_BARE_SIM_GAZEBO 44
#define PATTERN_TRANSLATE_AUTONOMOUS_PERFORMER_BARE_CRAZYFLIE_2_1 45
#define PATTERN_TRANSLATE_AUTONOMOUS_PERFORMER_BARE_SIM_GAZEBO 46
#define PATTERN_TRANSLATE_AUTONOMOUS_RELAY_BARE_CRAZYFLIE_2_1 47
#define PATTERN_TRANSLATE_OPERATOR_GUIDED_PERFORMER_BARE_CRAZYFLIE_2_1 48
#define PATTERN_UNDOCK_AUTONOMOUS_CHARGER_OUTBOUND_BARE_CRAZYFLIE_2_1 49

#endif /* SESHAT_CATALOG_DATA_H */
